export const SECTION_TYPES = [
  { type: "slideshow",       label: "Slideshow / Hero csúszka" },
  { type: "hero-light",      label: "Hero – Világos (bézs háttér)" },
  { type: "hero-dark",       label: "Hero – Sötét (fekete háttér)" },
  { type: "hero-image",      label: "Hero – Képes háttér (fotó)" },
  { type: "text-block",      label: "Szöveg blokk" },
  { type: "image-text",      label: "Kép + Szöveg (kép bal, szöveg jobb)" },
  { type: "text-image",      label: "Szöveg + Kép (szöveg bal, kép jobb)" },
  { type: "image-collage",   label: "Képkollázs (3-hasábos rács)" },
  { type: "gallery",         label: "Képgaléria" },
  { type: "banner",          label: "Banner kép" },
  { type: "rolunk",          label: "Rólunk blokk (zöld)" },
  { type: "steps",           label: "Lépések / Folyamat" },
  { type: "popular",         label: "Termékrács" },
  { type: "egyedi",          label: "Galéria rács (Egyedi)" },
  { type: "video",           label: "Videó szekció" },
  { type: "contact",         label: "Kapcsolatfelvétel (form)" },
];
