export const SECTION_TYPES = [
  { type: "slideshow",   label: "Képcsúszka (Slideshow hero)" },
  { type: "hero-light",  label: "Hero – Világos (bézs háttér)" },
  { type: "hero-dark",   label: "Hero – Sötét (fekete háttér)" },
  { type: "hero-image",  label: "Hero – Képes háttér (fotó)" },
  { type: "text-block",  label: "Szöveg blokk" },
  { type: "image-text",  label: "Kép + Szöveg (kéthasábos)" },
  { type: "card-grid",   label: "Kártya rács (termékek / kategóriák)" },
  { type: "gallery",     label: "Képgaléria (rács)" },
  { type: "banner",      label: "Banner kép" },
  { type: "stats",       label: "Statisztikák (számok)" },
  { type: "cta",         label: "CTA – Felhívás + telefon + gomb" },
  { type: "contact",     label: "Kapcsolatfelvétel (form)" },
  { type: "steps",       label: "Lépések / Folyamat" },
  { type: "popular",     label: "Termékrács (ár + link)" },
  { type: "egyedi",      label: "Galéria rács (Egyedi)" },
  { type: "rolunk",      label: "Rólunk blokk (olive)" },
];
