import type { MetadataRoute } from "next";

const BASE = "https://enzodesign.hu";

const PAGES = [
  { url: "/", priority: 1.0, changeFrequency: "weekly" },
  { url: "/rolunk", priority: 0.8, changeFrequency: "monthly" },
  { url: "/kapcsolat-es-rendeles", priority: 0.9, changeFrequency: "monthly" },
  { url: "/butoraink", priority: 0.9, changeFrequency: "weekly" },
  { url: "/butoraink/kanapek", priority: 0.8, changeFrequency: "weekly" },
  { url: "/butoraink/kanapek/olds-club-kanapek", priority: 0.7, changeFrequency: "monthly" },
  { url: "/butoraink/kanapek/ivone-kanapek", priority: 0.7, changeFrequency: "monthly" },
  { url: "/butoraink/kanapek/design-kanapek", priority: 0.7, changeFrequency: "monthly" },
  { url: "/butoraink/kanapek/chesterfield-kanapek", priority: 0.7, changeFrequency: "monthly" },
  { url: "/butoraink/kanapek/new-york-kanapek", priority: 0.7, changeFrequency: "monthly" },
  { url: "/butoraink/kanapek/joker-kanapek", priority: 0.7, changeFrequency: "monthly" },
  { url: "/butoraink/kanapek/cannes-kanapek", priority: 0.7, changeFrequency: "monthly" },
  { url: "/butoraink/fotelek", priority: 0.8, changeFrequency: "weekly" },
  { url: "/butoraink/fotelek/olds-club-fotel", priority: 0.7, changeFrequency: "monthly" },
  { url: "/butoraink/fotelek/ivone-fotel", priority: 0.7, changeFrequency: "monthly" },
  { url: "/butoraink/fotelek/design-fotel", priority: 0.7, changeFrequency: "monthly" },
  { url: "/butoraink/fotelek/chesterfield-fotel", priority: 0.7, changeFrequency: "monthly" },
  { url: "/butoraink/fotelek/new-york-fotel", priority: 0.7, changeFrequency: "monthly" },
  { url: "/butoraink/fotelek/joker-fotel", priority: 0.7, changeFrequency: "monthly" },
  { url: "/butoraink/fotelek/tovabbi-fotelek", priority: 0.6, changeFrequency: "monthly" },
  { url: "/butoraink/franciaagyak", priority: 0.7, changeFrequency: "monthly" },
  { url: "/butoraink/szek-zsamoly-falvedo", priority: 0.6, changeFrequency: "monthly" },
  { url: "/butoraink/egyedi-butor", priority: 0.8, changeFrequency: "monthly" },
  { url: "/rendeles-menete", priority: 0.8, changeFrequency: "monthly" },
  { url: "/butoraink/karpitoszovetek", priority: 0.6, changeFrequency: "monthly" },
  { url: "/chesterfield-kollekcio", priority: 0.7, changeFrequency: "monthly" },
  { url: "/olds-club-kollekcio", priority: 0.7, changeFrequency: "monthly" },
  { url: "/ivone-kollekcio", priority: 0.7, changeFrequency: "monthly" },
  { url: "/new-york-kollekcio", priority: 0.7, changeFrequency: "monthly" },
  { url: "/joker-kollekcio", priority: 0.7, changeFrequency: "monthly" },
  { url: "/design-butorok", priority: 0.7, changeFrequency: "monthly" },
  { url: "/chesterfield", priority: 0.8, changeFrequency: "monthly" },
  { url: "/chesterfield/a-chesterfield-kanape-eredete", priority: 0.6, changeFrequency: "monthly" },
  { url: "/chesterfield/chesterfield-stilus-es-formajegyek", priority: 0.6, changeFrequency: "monthly" },
  { url: "/chesterfield/chesterfield-anyagok-es-gyartai-technikak", priority: 0.6, changeFrequency: "monthly" },
  { url: "/chesterfield/chesterfield-a-modern-enteriorben", priority: 0.6, changeFrequency: "monthly" },
  { url: "/butorgyartas", priority: 0.6, changeFrequency: "monthly" },
  { url: "/butorgyartas/butorgyartas-folyamata", priority: 0.5, changeFrequency: "monthly" },
  { url: "/butorgyartas/tervezes", priority: 0.5, changeFrequency: "monthly" },
  { url: "/butorgyartas/anyagok", priority: 0.5, changeFrequency: "monthly" },
  { url: "/karpitozott-butor-uzleti-ugyfeleknek", priority: 0.7, changeFrequency: "monthly" },
  { url: "/butorvalaszto", priority: 0.7, changeFrequency: "monthly" },
  { url: "/akcio", priority: 0.8, changeFrequency: "weekly" },
  { url: "/butorbolt-zalaegerszeg", priority: 0.8, changeFrequency: "monthly" },
  { url: "/butorbolt-kaposvar", priority: 0.8, changeFrequency: "monthly" },
  { url: "/butorbolt-keszthely", priority: 0.8, changeFrequency: "monthly" },
  { url: "/butorbolt-siofok", priority: 0.8, changeFrequency: "monthly" },
  { url: "/butorbolt-tapolca", priority: 0.8, changeFrequency: "monthly" },
  { url: "/butorbolt-marcali", priority: 0.8, changeFrequency: "monthly" },
  { url: "/butorbolt-kormend", priority: 0.8, changeFrequency: "monthly" },
  { url: "/butorbolt-barcs", priority: 0.8, changeFrequency: "monthly" },
  { url: "/butorbolt-szigetvar", priority: 0.8, changeFrequency: "monthly" },
  { url: "/butorbolt-nagykanizsa", priority: 0.9, changeFrequency: "monthly" },
  { url: "/butorbolt-budapest", priority: 0.9, changeFrequency: "monthly" },
  { url: "/blog", priority: 0.7, changeFrequency: "weekly" },
  { url: "/blog/butorbolt-nagykanizsán", priority: 0.6, changeFrequency: "monthly" },
  { url: "/blog/kanape-zalaegerszegen", priority: 0.6, changeFrequency: "monthly" },
  { url: "/blog/bor-fotel", priority: 0.6, changeFrequency: "monthly" },
  { url: "/blog/modern-chesterfield-kanape", priority: 0.6, changeFrequency: "monthly" },
  { url: "/blog/agyazhato-chesterfield-kanape", priority: 0.6, changeFrequency: "monthly" },
  { url: "/blog/egyedi-butor-keszittetes", priority: 0.6, changeFrequency: "monthly" },
  { url: "/blog/melyik-chesterfield-butor-illik-hozzad", priority: 0.6, changeFrequency: "monthly" },
  { url: "/blog/miert-eri-meg-kozvetlen-a-butorgyartotol-vasarlni", priority: 0.6, changeFrequency: "monthly" },
  { url: "/blog/miert-idotallo-valasztas-a-chesterfield-kanape", priority: 0.6, changeFrequency: "monthly" },
  { url: "/blog/tomorfa-butor", priority: 0.6, changeFrequency: "monthly" },
  { url: "/vasarloi-visszajelzesek", priority: 0.6, changeFrequency: "monthly" },
] as const;

export default function sitemap(): MetadataRoute.Sitemap {
  return PAGES.map(({ url, priority, changeFrequency }) => ({
    url: `${BASE}${url}`,
    changeFrequency,
    priority,
  }));
}
